vllm-project/semantic-router

- bench/bench_plot.py
- bench/router_reason_bench.py
- src/semantic-router/pkg/extproc/request_handler.go
> fix: remove no needed todo and verify CI

- bench/OWNER
- website/OWNER
project: add bench and site owners
Fixes #
> project: add bench and site owners

- .github/workflows/docker-publish.yml
- .github/workflows/docker-release.yml
- deploy/kubernetes/deployment.yaml
- deploy/kubernetes/kustomization.yaml
> chore: unify docker images

- src/training/model_eval/mmlu_pro_vllm_eval.py
- src/training/model_eval/result_to_config.py
- website/docs/getting-started/configuration.md
Doc improvement to explain the config.yaml generation workflow.
Fixes #
> doc: update workflow to create config.yaml

- Makefile
- bench/run_bench.sh
- Add rust installation if it is not installed yet, per doc instructions
- Expose bench params in env var
Fixes #
> chore: 1) install rust if not present 2) expose bench params in env var

- src/training/classifier_model_fine_tuning/go.mod
- src/training/pii_model_fine_tuning/go.mod
- src/training/prompt_guard_fine_tuning/go.mod
fix: correct candle-binding replace path in go.mod files
**What this PR does / why we need it**: 
candle-binding replace path in go.mod files is incorrect.
`make test-pii-classifier` will fail.
Fixes #
Release Notes: No
> fix: correct candle-binding replace path in go.mod files

- config/config.yaml
- src/semantic-router/pkg/config/config.go
- src/semantic-router/pkg/extproc/request_handler.go
- src/semantic-router/pkg/extproc/response_handler.go
- src/semantic-router/pkg/metrics/metrics.go
- src/semantic-router/pkg/observability/logging.go
- website/docs/api/router.md
- website/docs/getting-started/configuration.md
- metrics: add llm_model_cost_usd_total and llm_routing_reason_codes_total
- docs: add pricing section and cost/routing metrics
- chore: normalize config/config.yaml line endings
Fixes https://github.com/vllm-project/semantic-router/issues/49
> feat(observability): structured JSON logs and event fields

- docker-compose.yml
https://docs.docker.com/reference/compose-file/version-and-name/
`version` field is onsolete
> chore: remove docker compose version, because verion is obsolete

- src/semantic-router/pkg/utils/classification/classifier.go
chore: Normalize comment punctuation to use English period
Fixes #
> chore: Normalize comment punctuation to use English period

- Makefile
test: add go vet to CI
[Motivation](https://github.com/vllm-project/semantic-router/pull/77#issuecomment-3263887345)
By adding `go vet` to the CI pipeline, we are able to catch common code style issues and potential bugs early. 
Fixes #
> test: add go vet to CI

- config/config.yaml
- src/semantic-router/pkg/config/config.go
- src/semantic-router/pkg/extproc/reason_mode_config_test.go
- src/semantic-router/pkg/extproc/reason_mode_selector.go
- src/semantic-router/pkg/extproc/reason_mode_selector_test.go
- src/semantic-router/pkg/extproc/reasoning_integration_test.go
- website/docs/getting-started/configuration.md
If the model doesn't support reasoning, don't set the reasoning effort in API call.
This is a regression when reasoning mode support is added
Fixes #
> fix: don't set reasoning effort for non-reasoning models

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- README.md
- candle-binding/README.md
- deploy/kubernetes/README.md
- docker/README.md
- e2e-tests/README.md
- markdownlint.yaml
- src/training/dual_classifier/DUAL_CLASSIFIER_SYSTEM_TEST_SUMMARY.md
- src/training/dual_classifier/README.md
- src/training/dual_classifier/trained_model/README.md
- website/README.md
- website/blog/2025-09-06-welcome.md
- website/docs/api/classification.md
- website/docs/api/router.md
- website/docs/architecture/system-architecture.md
- website/docs/getting-started/configuration.md
- website/docs/getting-started/installation.md
- website/docs/getting-started/reasoning-routing-quickstart.md
- website/docs/intro.md
- website/docs/overview/mixture-of-models.md
- website/docs/overview/semantic-router-overview.md
- website/docs/training/training-overview.md
> docs: add markdown lint check and fix md lint style

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- .yamllint
- Makefile
- config/cache/milvus.yaml
- config/config.yaml
- deploy/kubernetes/config.yaml
- deploy/kubernetes/deployment.yaml
- deploy/kubernetes/kustomization.yaml
- docker-compose.yml
> infra: add yaml lint check and fix yaml style

- Makefile
- candle-binding/semantic-router_test.go
- candle-binding/src/modernbert.rs
perf: enable concurrent classification via Arc+clone
This PR updates the `MODERNBERT_CLASSIFIER` definition to use `Arc<ModernBertClassifier>` so that the global lock is only held for initialization. Subsequent calls now clone the `Arc` and release the lock immediately, allowing concurrent inference without serialization.
[concurrency-safe guarantee]
For now, only `MODERNBERT_CLASSIFIER` is changed; `MODERNBERT_PII_CLASSIFIER` and `MODERNBERT_JAILBREAK_CLASSIFIER` remain unchanged, so that we can focus discussion on this design and trade-offs before extending it further.
Fixes #
> perf: enable concurrent classification via Arc+clone

- website/docs/getting-started/installation.md
docs: update go version requirement and test tip for model downloads
Release Notes: No
> docs(installation): update Go version requirement and add test tip for model downloads

- CONTRIBUTING.md
- src/semantic-router/pkg/cache/cache_interface.go
- src/semantic-router/pkg/cache/cache_test.go
- src/semantic-router/pkg/cache/inmemory_cache.go
- src/semantic-router/pkg/cache/milvus_cache.go
- src/semantic-router/pkg/extproc/error_metrics_test.go
- src/semantic-router/pkg/extproc/metrics_integration_test.go
- src/semantic-router/pkg/extproc/request_handler.go
- src/semantic-router/pkg/extproc/response_handler.go
- src/semantic-router/pkg/extproc/router.go
- src/semantic-router/pkg/extproc/test_utils_test.go
- src/semantic-router/pkg/extproc/testing_helpers_test.go
- tools/make/common.mk
- tools/make/milvus.mk
fix: use request id to locate the correct cache entry to update
The major change:
1. Update the cache interface to use request id to locate the cache entry
Other changes:
-   Added `request_id` to Milvus storage.
-   Replaced the `insert` operation with `upsert` in `MilvusCache.addEntry`. Previously, it always inserted two entries into storage—one for `AddPendingRequest` and another for `UpdateWithResponse`. Now, it updates the entry if a cache entry with the same `request_id` already exists.
-   Removed the logic that added an unknown cache entry when no cache entry was found in `UpdateWithResponse`. I think it's not useful because we this unknown cache entry doesn't have `model` field.
-   Removed `pendingRequests` and …
> fix: use request id to locate the correct cache entry to update

- Dockerfile.extproc
When exec `docker-compose up --build` will a error `make[1]: tools/make/models.mk: No such file or directory`, to check after is `tools` dir miss copy.
Fixes #
> fix: miss copy tools dir in dockerfile

- .gitignore
feat: Update .gitignore for AI docs
Avoid pushing AI docs(cursor, claude, copilot) to the remote repo mistakenly.
> feat: Update .gitignore for AI docs

- deploy/kubernetes/deployment.yaml
This PR adds two security attributes to container definitions that improve the security of the containers when being run in Kubernetes.
At the same time, this PR reduces the noise of vulnerabilitiy scanners because they normally raise alerts when these attributes are missing.
> security: add security attributes related to root usage to container definitions

- config/grafana/dashboards.yaml
- config/grafana/datasource.yaml
- config/prometheus.yaml
- docker-compose.yml
- website/docs/getting-started/observability.md
- website/sidebars.js
feat: set up Grafana and Prometheus for Observability and Monitoring
Focusing on local Docker Compose setting up Grafana+Prometheus MVP
- Add configurations `prometheus.yaml` and `grafana/datasource.yaml`, `grafana/dashboards.yaml` in `config/`
- Add services of Prometheus and Grafana in `docker-compose.yml`
- Add doc for setting up local Docker Compose in `website/docs/observability.md`
Fixes #164
> feat: set up Grafana and Prometheus for Observability and Monitoring

- e2e-tests/01-envoy-extproc-test.py
01-envoy-extproc-test.py with ExtProc-specific functionality tests and implements cache bypass using unique UUIDs.
Test Coverage:
1. test_request_headers_propagation
What: Tests that custom headers flow correctly through the ExtProc How:
- Sends request with custom headers: X-Test-Trace-ID, X-Original-Model
- Verifies ExtProc doesn't break header handling
- Checks response contains proper Content-Type and model fields ExtProc Value: Ensures headers aren't corrupted during ExtProc processing
2. test_extproc_body_modification
What: Tests that ExtProc can inspect/modify request and response bodies How:
- Sends request with custom field: "test_field": "should_be_preserved"
- Uses header X-Test-Body-Modification: true to signal ExtProc
- Verifies response is valid and processing succeeded …
> feat: implement comprehensive ExtProc testing with cache bypass

- src/semantic-router/pkg/extproc/models_endpoint_test.go
- src/semantic-router/pkg/extproc/request_handler.go
feat: support /v1/models in direct response
> feat: support /v1/models in direct response

- e2e-tests/02-router-classification-test.py
- e2e-tests/README.md
All 3 tests now pass successfully with verified classification routing:
- Category Classification: Math→Model-B, CS→Model-B, Business→Model-A, History→Model-A ✅
- Classification Consistency: Same query routes to same model ✅
Release Notes: No
> e2e test: 02-router-classification: verify router classification

- e2e-tests/03-classification-api-test.py
- e2e-tests/README.md
The 03-classification-api-test validates the standalone Classification API service
Key Differences between this test and the 02-classificatoin test: 
Architecture: ExtProc is integrated with Envoy for transparent routing; Classification API is a standalone HTTP service
Use Case: ExtProc is for LLM routing; Classification API is for direct text categorization
Response: ExtProc returns LLM completions; Classification API returns category labels
Integration: ExtProc uses classifier directly; Classification API uses service wrapper layer
NOTE: this test exposes a bug in the server.go functionality.  related to #303 
> 03 classification api test

- src/semantic-router/pkg/services/classification_test.go
Fix the unit test that uses new function in #332 
Fixes #
> fix: use classification unit test

- tools/mock-vllm/app.py
add direct execution support for local development
This PR adds a __main__ entry point to app.py, allowing the FastAPI application to be started directly using python app.py without requiring Docker or a full vLLM environment.
This change improves the local development experience by enabling a mock-based setup for users who have installed dependencies locally. It aligns with the "Install in Local" documentation and reduces the barrier to entry for testing.
> feat(app): add direct execution support for local development

- docs/design/additional-prompt-classification-routing.md
Design doc for #313 #200 
Fixes #
> feat: add design spec for additional prompt classification
